name: 删除特定字段

on:
  workflow_dispatch: # 手动触发工作流程
  schedule:
    - cron: '0 */6 * * *' # 配置定时执行的时间间隔，例如每天午夜执行

jobs:
  remove_lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove lines from chongxie.txt
      run: |
        # 下载指定文件的内容到临时文件
        curl -o chongxie.txt https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt
        curl -o test.py https://raw.githubusercontent.com/SFDingDAng/chongxie/main/test.py

        # 使用 python 删除包含指定内容的行
        python3 test.py

        sed -n '1748p' chongxie.txt

        # 将修改后的内容覆盖回原文件
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add chongxie.txt
        git commit -m "Remove lines from chongxie.txt"
        git push
