name: 删除特定字段

on:
  workflow_dispatch: # 手动触发工作流程
  schedule:
    - cron: '0 0 * * *' # 配置定时执行的时间间隔，例如每天午夜执行

jobs:
  remove_lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove lines from chongxie.txt
      run: |
        # 下载指定文件的内容到临时文件
        curl -o chongxie.txt https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt

        # 使用 sed 命令删除包含指定内容的行
        sed -i '/\^http\[s\]\?\:\\\/\\\/magev6\\\.if\\\.qidian\\\.com\\\/argus\\\/api\\\/v1\\\/bookshelf\\\/refresh url reject-200/d' chongxie.txt

        sed -n '1748' chongxie.txt

        # 将修改后的内容覆盖回原文件
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add chongxie.txt
        git commit -m "Remove lines from chongxie.txt"
        git push
